dist: trusty
sudo: required
language: node_js
node_js:
- '6'
- '8'
script:
- npm test -- --coverage
after_script:
- if [[ `node --version` == *v6* ]]; then cat ./coverage/lcov.info | ./node_modules/.bin/codeclimate-test-reporter;
  fi
env:
  global:
    secure: Tjv451jv8ksGOEcd3g/5zffmUvrKxfv5mSZ8uZ//xsL5GzZ1IfxQd7HvM84mAx/it6Y5tnWh/4KkoTJck0NRw41ZAFB6FsJkEZIy8w2/EdRseSznjBwEgHLE36m3YPQ+ktGHMffLxEanPGy2pymhkrLmIruupPKbpPgChKG9oWU=
